apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-built-in-registry-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: localhost:32000/nginx1.21:registry
          ports:
            - containerPort: 80
