apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
        - name: example-job
          image: busybox
          command: ["echo", "echo example Job Pod is Running"]
      restartPolicy: Never
      backoffLimit: 4
